/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FakeStoreAPI
 * A free fake API for testing and prototyping e-commerce applications.
 * OpenAPI spec version: 2.1.8
 */
import type { Product } from './product';

export interface Cart {
  id?: number;
  userId?: number;
  products?: Product[];
}
